os: linux
dist: xenial
language: python
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - python -m pip install poetry-dynamic-versioning
  - source $HOME/.poetry/env
  - echo VIRTUAL_ENV=$VIRTUAL_ENV
script:
  - poetry build
  - pip install -U deepqmc[wf,train,cli,test] --pre -f ./dist
  - coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
before_cache:
  - coverage xml
  - pip uninstall -y deepqmc
cache:
  directories:
    - $VIRTUAL_ENV/bin
    - $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
jobs:
  include:
    - name: Style
      python: 3.7
      install:
        - pip install -U black flake8 flake8-bugbear flake8-comprehensions flake8-quotes pep8-naming isort pydocstyle
      script:
        - flake8
        - black . --check
        - isort . --check
        - pydocstyle src
      env: CACHE_NAME=lint
    - python: 3.7
    - python: 3.8
    - name: Documentation
      python: 3.7
      install:
        - pip install -U "sphinx<3" sphinxcontrib-katex toml
      script:
        - sphinx-build -W -E doc doc/build
      env: CACHE_NAME=deploy
      workspaces:
        create:
          name: ws1
          paths:
            - doc/build
    - stage: deploy
      name: Documentation
      language: minimal
      install: skip
      script: skip
      before_cache: skip
      if: (branch = master) AND (NOT type IN (pull_request))
      workspaces:
        use: ws1
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: doc/build
        repo: deepqmc/deepqmc.github.io
        target_branch: master
