name: Lint
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  flake8:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install 'flake8' flake8-bugbear flake8-comprehensions flake8-quotes pep8-naming
      - uses: actions/checkout@v2
      - run: flake8
  black:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install black
      - uses: actions/checkout@v2
      - run: black . --check --diff --preview
  isort:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install isort
      - uses: actions/checkout@v2
      - run: isort . --check
  pydocstyle:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install pydocstyle
      - uses: actions/checkout@v2
      - run: pydocstyle src
  mypy:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mypy types-PyYAML types-toml
      - uses: actions/checkout@v2
      - run: mypy --ignore-missing-imports src
  codespell:
    if: github.event_name != 'schedule' || github.repository == 'deepqmc/deepqmc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install codespell
      - uses: actions/checkout@v2
      - run: codespell
